---
driver:
  name: vagrant
  network:
    - ["private_network", { ip: "192.168.33.33" }]

provisioner:
  name: salt_solo
  formula: etcd


platforms:
  - name: ubuntu-14.04

suites:
  - name: default
