sudo: required

language: python

services:
  - etcd

before_install:
  - bundle install

env:
  matrix:
    - INSTANCE: default-ubuntu-1804
    - INSTANCE: default-debian-stretch
    - INSTANCE: version-339-ubuntu-1804
    - INSTANCE: version-339-centos7

script:
  - bundle exec kitchen verify ${INSTANCE}
