language: python
python:
  - '2.7'

env:
  global:
    - BS_PIP_ALLOWED=1
    - BS_ECHO_DEBUG=1
    - SALT_ARGS="-l debug --local --retcode-passthrough --pillar-root=test/pillar --file-root=$PWD"

before_install:
  - sudo apt-get update
  - curl -L http://bootstrap.saltstack.org | sudo sh -E -s -- -P stable

install:
  - sudo mkdir -p /srv && sudo ln -sfn $PWD /srv/formula
  # See what kind of travis box you're on to help with making your states
  # compatible with travis
  - sudo salt-call grains.items --local  

  # Additional debug help
  - sudo cat /var/log/salt/*

  # See what kind of travis box you're on
  # to help with making your states compatible with travis
  - sudo salt-call grains.items --local

script:
  - sudo salt-call state.show_highstate $SALT_ARGS

